apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core/
  - rabbitmq/
  # - manifests/
  # - volume-creation/
  # - demo-metrics-adapter/
  # - business-demo/
  # - kubernetes-management/
