${SPARQL_PREFIXES}
DELETE { ?action ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::fromState} . }
INSERT { ?action ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::toState} . }
WHERE { 
  ?action ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::fromState} .
  FILTER(?action = ${IRI::actionId})
}
