${SPARQL_PREFIXES}
DELETE { ${IRI::actionId} ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::fromState} . }
INSERT { ${IRI::actionId} ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::toState} . }
WHERE { 
  ${IRI::actionId} ${PREFIX::ACTIONS_PREFIX}:hasState ${IRI::fromState} .
}
