${SPARQL_PREFIXES}
SELECT DISTINCT ?window ?lastTransition
WHERE {
  ?action ${PREFIX::ACTIONS_PREFIX}:idempotencyWindowSeconds ?window .
  ?action ${PREFIX::ACTIONS_PREFIX}:hasLastTransitionTimestamp ?lastTransition .
  FILTER(?action = ${IRI::actionId})
}
