SELECT DISTINCT ?action ?intent ?target ?protocol ?instruction ?method ?payload ?expectedStatusCode
       ?preId ?preType ?prePolicy 
       ?postId ?postType ?postPolicy 
WHERE { 
  ?action moam:targetsEntity ${resourceIri} . 
  BIND(${resourceIri} AS ?target)
  ?action a ?intent . 
  OPTIONAL { ?action moam:hasExecutionProtocol ?protocol } . 
  OPTIONAL { ?action moam:hasExecutionInstruction ?instruction } . 
  OPTIONAL { ?action moam:hasHttpMethod ?method } . 
  OPTIONAL { ?action moam:hasExecutionPayload ?payload } . 
  OPTIONAL { ?action moam:hasExpectedStatusCode ?expectedStatusCode } . 
  OPTIONAL { 
    ?action moam:hasPreCondition ?preId . 
    ?preId a ?preType . 
    ?preId moam:policyQueryString ?prePolicy . 
  } . 
  OPTIONAL { 
    ?action moam:hasPostCondition ?postId . 
    ?postId a ?postType . 
    ?postId moam:policyQueryString ?postPolicy . 
  } . 
   
}
