apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphdb
  namespace: graphdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphdb
  template:
    metadata:
      labels:
        app: graphdb
    spec:
      containers:
        - name: graphdb
          image: ontotext/graphdb:11.3.3
          ports:
            - containerPort: 7200
          env:
            - name: GDB_HEAP_SIZE
              value: "2G"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
