apiVersion: v1
kind: Service
metadata:
  name: hephaestus
  namespace: hephaestus
  labels:
    app: hephaestus
spec:
  selector:
    app: hephaestus
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP
