apiVersion: apps/v1
kind: Deployment
metadata:
  name: metis
  namespace: metis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metis
  template:
    metadata:
      labels:
        app: metis
    spec:
      serviceAccountName: metis
      containers:
        - name: metis
          image: docker.io/sglomski/metis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
              name: grpc
          env:
            - name: METIS_GRAPHDB_URL
              value: "http://graphdb.graphdb.svc.cluster.local:7200"
            - name: METIS_GRAPHDB_REPOSITORYID
              value: "amocna"
            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: METIS_SENSOR_ENABLED
              value: "true"
            - name: METIS_SENSOR_NAMESPACES
              value: "hephaestus-business"
