apiVersion: apps/v1
kind: Deployment
metadata:
  name: palamedes
  namespace: hephaestus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palamedes
  template:
    metadata:
      labels:
        app: palamedes
    spec:
      containers:
        - name: palamedes
          image: sglomski/palamedes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: GRAPHDB_URL
              value: "http://graphdb.graphdb.svc.cluster.local:7200"
            - name: GRAPHDB_REPO
              value: "amocna"
            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
            - name: PROMETHEUS_URL
              value: "http://prometheus.monitoring.svc.cluster.local:9090"
