FROM rabbitmq:4.0-management

# Install curl to download the plugin
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Download the RabbitMQ Delayed Message Exchange plugin
# Matching the RabbitMQ 4.0 version
RUN curl -L https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez > /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.0.2.ez

# Enable the plugin
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange
