PREFIX moam: <http://www.semanticweb.org/patryk/ontologies/2026/4/MoaMont#>
DELETE {
  ?action ?p ?o .
  ?s ?p2 ?action .
}
WHERE {
  ?action a moam:AutonomicAction .
  ?action ?p ?o .
  OPTIONAL { ?s ?p2 ?action . }
}
