apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-stress
  namespace: default
spec:
  replicas: 0 # Start with 0, manually scale up to trigger scenarios
  selector:
    matchLabels:
      app: cluster-stress
  template:
    metadata:
      labels:
        app: cluster-stress
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-worker-3
      containers:
        - name: stress
          image: progrium/stress
          args:
            [
              "--cpu",
              "2",
              "--io",
              "1",
              "--vm",
              "1",
              "--vm-bytes",
              "500M",
              "--timeout",
              "600s",
            ]
            resources:
            limits:
              cpu: "300m"
              memory: "600Mi"
            requests:
              cpu: "300m"
              memory: "600Mi"
